#!/bin/bash
process='NormalApp'
echo "=============================================================="
echo "默认调试的app是：$process, 如果需要改其他的，请编辑本脚本"
echo "=============================================================="
debugserver localhost:30011 -a $process
